-- Final Project
-- Supplier Status Report
-- M. Barry
-- IS380
-- Spring 2020

SET LINESIZE 83;
SET PAGESIZE 120;

TTITLE CENTER "      -------- Supplier's Order Status Report -------- Page:" SQL.PNO SKIP 3;

COLUMN SUPPLIER_CODE HEADING "Supplier|Code"
COLUMN SUPPLIER_NAME HEADING "Supplier|Name"
COLUMN ORD_NUM HEADING "Order|No."
COLUMN "Order Date" HEADING "Order|Date"
COLUMN "Receive Date" HEADING "Recieve|Date"
COLUMN "NOD" HEADING "Number|of Days"
COLUMN "NOD" FORMAT 9.99

BREAK ON SUPPLIER_CODE SKIP 1 ON SUPPLIER_NAME
COMPUTE AVG LABEL 'Avg Days' OF "NOD" ON SUPPLIER_CODE

SELECT S.SUPPLIER_CODE, S.SUPPLIER_NAME, O.ORD_NUM, TO_CHAR(O.ORD_DATE, 'MM/DD/YY') "Order Date", TO_CHAR(O.ORD_RECDATE, 'MM/DD/YY') "Receive Date", O.ORD_RECDATE - O.ORD_DATE "NOD",
	CASE
		WHEN O.ORD_RECDATE IS NULL
		THEN 'Open'
		ELSE 'Complete'
	END
	AS "STATUS"
FROM SUPPLIER S, ORD O
WHERE S.SUPPLIER_CODE = O.SUPPLIER_CODE
ORDER BY S.SUPPLIER_CODE;


